#include "./uniforms_transform"
#include "./uniforms_volume"
#include "./uniforms_box"
#include "./uniforms_ray"
#include "./uniforms_textures"
#include "./uniforms_shading"
#include "./uniforms_debug"
